const { deepFreeze } = require("./sd15");

export const SD15_BASE_PAGE_CONFIG = deepFreeze({
    ids: {
        modelSelect: "model_select",
        prompt: "prompt",
        negativePrompt: "negative_prompt",
        scheduler: "scheduler",
        seed: "seed",
        steps: "steps",
        cfg: "cfg",
        numImages: "num_images",
        width: "width",
        height: "height",
        hiresEnabled: "hires_enabled",
        hiresScale: "hires_scale",
        clipSkip: "clip_skip",
        weightingPolicy: "weighting_policy",
        controlnetEnabled: "controlnet-enabled",
        controlnetConditioningScale: "controlnet_conditioning_scale",
        controlGuidanceStart: "control_guidance_start",
        controlGuidanceEnd: "control_guidance_end",
        controlnetGuessMode: "controlnet_guess_mode",
        controlnetCompatMode: "controlnet_compat_mode",
        generateButton: "generate-button",
        controlnetStatus: "controlnet-status",
    },
    tasks: {
        text2img: "sd15.text2img",
        controlnetText2img: "sd15.controlnet.text2img",
        hiresFix: "sd15.hires_fix",
    },
    fallbackDefaults: {
        prompt: "",
        negative_prompt: "",
        steps: 20,
        cfg: 7.5,
        scheduler: "euler",
        width: 512,
        height: 512,
        hires_scale: 1.0,
        clip_skip: 1,
        num_images: 1,
        weighting_policy: "diffusers-like",
        controlnet_conditioning_scale: 1.0,
        control_guidance_start: 0.0,
        control_guidance_end: 1.0,
        controlnet_compat_mode: "warn",
        model: null,
        modelSelectOption: "stable-diffusion-v1-5",
    },
    mappings: {
        catalogDefaults: {
            text2img: {
                steps: "steps",
                cfg: "cfg",
                width: "width",
                height: "height",
                num_images: "num_images",
                clip_skip: "clip_skip",
                weighting_policy: "weighting_policy",
            },
            controlnetText2img: {
                steps: "steps",
                cfg: "cfg",
                width: "width",
                height: "height",
                num_images: "num_images",
                clip_skip: "clip_skip",
                controlnet_conditioning_scale: "controlnet_conditioning_scale",
                control_guidance_start: "control_guidance_start",
                control_guidance_end: "control_guidance_end",
                controlnet_compat_mode: "controlnet_compat_mode",
            },
            hiresFix: {
                hires_scale: "hires_scale",
            },
        },
        presetTextOrNumberFields: {
            prompt: "prompt",
            negative_prompt: "negative_prompt",
            steps: "steps",
            cfg: "cfg",
            scheduler: "scheduler",
            seed: "seed",
            width: "width",
            height: "height",
            hires_scale: "hires_scale",
            clip_skip: "clip_skip",
            num_images: "num_images",
            weighting_policy: "weighting_policy",
            controlnet_conditioning_scale: "controlnet_conditioning_scale",
            control_guidance_start: "control_guidance_start",
            control_guidance_end: "control_guidance_end",
            controlnet_compat_mode: "controlnet_compat_mode",
        },
        presetBooleanFields: {
            hires_enabled: "hires_enabled",
            controlnet_enabled: "controlnet-enabled",
            controlnet_guess_mode: "controlnet_guess_mode",
        },
    },
});
