const TASK_ANIMATEDIFF_TEXT2VIDEO = "sd15.animatediff.text2video";

const animatediff = AnimateDiffController.create({
    taskType: TASK_ANIMATEDIFF_TEXT2VIDEO,
    fallbackModel: {
        value: "stable-diffusion-v1-5",
        label: "stable-diffusion-v1-5 (sd15, diffusers)",
    },
    fields: [
        { element: "prompt", key: "prompt", fallback: "" },
        { element: "negative_prompt", key: "negative_prompt", fallback: "" },
        { element: "steps", key: "steps", type: "number", integer: true, fallback: 25 },
        { element: "cfg", key: "cfg", type: "number", fallback: 7.5 },
        { element: "scheduler", key: "scheduler", fallback: "ddim" },
        { element: "seed", key: "seed", type: "seed" },
        { element: "width", key: "width", type: "number", integer: true, fallback: 512 },
        { element: "height", key: "height", type: "number", integer: true, fallback: 512 },
        {
            element: "motion_adapter",
            key: "motion_adapter",
            fallback: "guoyww/animatediff-motion-adapter-v1-5-2",
        },
        { element: "num_frames", key: "num_frames", type: "number", integer: true, fallback: 16 },
        { element: "fps", key: "fps", type: "number", integer: true, fallback: 8 },
        { element: "num_videos", key: "num_videos", type: "number", integer: true, fallback: 1 },
        { element: "free_noise_enabled", key: "free_noise_enabled", type: "checkbox" },
        {
            element: "free_noise_context_length",
            key: "free_noise_context_length",
            type: "number",
            integer: true,
            fallback: 16,
        },
        {
            element: "free_noise_context_stride",
            key: "free_noise_context_stride",
            type: "number",
            integer: true,
            fallback: 4,
        },
        { element: "free_init_enabled", key: "free_init_enabled", type: "checkbox" },
        {
            element: "free_init_num_iters",
            key: "free_init_num_iters",
            type: "number",
            integer: true,
            fallback: 3,
        },
        {
            element: "free_init_use_fast_sampling",
            key: "free_init_use_fast_sampling",
            type: "checkbox",
        },
        { element: "free_init_method", key: "free_init_method", fallback: "butterworth" },
        {
            element: "free_init_order",
            key: "free_init_order",
            type: "number",
            integer: true,
            fallback: 4,
        },
        {
            element: "free_init_spatial_stop_frequency",
            key: "free_init_spatial_stop_frequency",
            type: "number",
            fallback: 0.25,
        },
        {
            element: "free_init_temporal_stop_frequency",
            key: "free_init_temporal_stop_frequency",
            type: "number",
            fallback: 0.25,
        },
        { element: "clip_skip", key: "clip_skip", type: "number", integer: true, fallback: 1 },
        { element: "weighting_policy", key: "weighting_policy", fallback: "diffusers-like" },
        { element: "model_select", key: "model", fallback: null },
    ],
    catalogBindings: {
        steps: "steps",
        cfg: "cfg",
        width: "width",
        height: "height",
        motion_adapter: "motion_adapter",
        num_frames: "num_frames",
        fps: "fps",
        num_videos: "num_videos",
        free_noise_context_length: "free_noise_context_length",
        free_noise_context_stride: "free_noise_context_stride",
        free_init_num_iters: "free_init_num_iters",
        free_init_method: "free_init_method",
        free_init_order: "free_init_order",
        free_init_spatial_stop_frequency: "free_init_spatial_stop_frequency",
        free_init_temporal_stop_frequency: "free_init_temporal_stop_frequency",
        clip_skip: "clip_skip",
        weighting_policy: "weighting_policy",
    },
});

GenerationPage.runWhenDomReady(animatediff.init);
